verifier:
  service:
    plugins:
      repository:
        url: "https://plugins.jetbrains.com"
    enable:
      plugin:
        verifier:
          service: false
      feature:
        extractor:
          service: false
      available:
        ide:
          service: false
    feature:
      extractor:
        ide:
          build: "IU-183.5912.21"
    scheduler:
      period:
        seconds: 10
    task:
      manager:
        concurrency: 8
    clear:
      corrupted:
        database: true
