verifier:
  service:
    plugins:
      repository:
        url: "https://plugins.jetbrains.com"
    enable:
      plugin:
        verifier:
          service: false
      feature:
        extractor:
          service: false
      available:
        ide:
          service: false